Added preflight auth angular
AITestingOrg/authentication-service pull request #7
Opened 2018-07-13 18:54 UTC by jusoto

2018-07-13 19:58 UTC, ghost requested changes

2018-07-13 19:58 UTC, iplonk3 commented on build.gradle
> +		mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Edgware.SR2'
Shouldn't this be SR3?

2018-07-13 19:58 UTC, iplonk3 commented on docker-compose-local.yml
> +      - discovery-service
Need to take out the dash

2018-07-13 19:58 UTC, iplonk3 commented on src/main/resources/application.yml
> +        defaultZone: http://${DOCKER_MACHINE_IP:discovery-service}:8761/eureka/
No dash

2018-07-13 19:58 UTC, iplonk3 commented on src/main/resources/application.yml
> +        defaultZone: http://discovery-service:8761/eureka/
No dash

2018-07-13 21:32 UTC, ghost approved these changes

2018-07-17 17:51 UTC, Richardj52 approved these changes

2018-07-17 17:52 UTC, merged